-- Schéma initial PostgreSQL, exporté depuis la base de développement (sans données).
-- Toute évolution ultérieure doit être ajoutée dans une nouvelle migration V*.sql.

CREATE TABLE analyse_lait (
    id bigint NOT NULL,
    date_analyse timestamp(6) without time zone NOT NULL,
    observation character varying(1000),
    resultat character varying(255) NOT NULL,
    type_analyse character varying(120) NOT NULL,
    unite character varying(40),
    lot_lait_id bigint NOT NULL
);


--
-- Name: analyse_lait_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE analyse_lait ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME analyse_lait_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cave; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE cave (
    id bigint NOT NULL,
    active boolean NOT NULL,
    age_max_jours integer NOT NULL,
    age_min_jours integer NOT NULL,
    description character varying(500),
    humidite numeric(5,2) NOT NULL,
    nom character varying(120) NOT NULL,
    temperature numeric(6,2) NOT NULL
);


--
-- Name: cave_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE cave ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cave_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE client (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    adresse character varying(255),
    nom character varying(160) NOT NULL,
    telephone character varying(255),
    type_client character varying(30) NOT NULL,
    CONSTRAINT client_type_client_check CHECK (((type_client)::text = ANY ((ARRAY['EPICERIE'::character varying, 'MARCHE'::character varying, 'VENTE_DIRECTE'::character varying])::text[])))
);


--
-- Name: client_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: commande; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE commande (
    id bigint NOT NULL,
    date_commande date NOT NULL,
    date_livraison_souhaitee date NOT NULL,
    numero_commande character varying(255) NOT NULL,
    observations character varying(1000),
    statut character varying(30) NOT NULL,
    client_id bigint NOT NULL,
    utilisateur_createur_id bigint,
    CONSTRAINT commande_statut_check CHECK (((statut)::text = ANY ((ARRAY['BROUILLON'::character varying, 'CONFIRMEE'::character varying, 'EN_PREPARATION'::character varying, 'PRETE'::character varying, 'LIVREE'::character varying, 'ANNULEE'::character varying])::text[])))
);


--
-- Name: commande_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE commande ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME commande_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configuration_emballage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE configuration_emballage (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    quantite_par_unite numeric(19,4) NOT NULL,
    emballage_id bigint NOT NULL,
    fromage_id bigint NOT NULL
);


--
-- Name: configuration_emballage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE configuration_emballage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME configuration_emballage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consommation_emballage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE consommation_emballage (
    id bigint NOT NULL,
    cout_unitaire_reference numeric(19,4) NOT NULL,
    date_heure timestamp(6) without time zone NOT NULL,
    etape character varying(30) NOT NULL,
    quantite integer NOT NULL,
    emballage_id bigint NOT NULL,
    lot_affinage_id bigint NOT NULL,
    utilisateur_id bigint NOT NULL,
    CONSTRAINT consommation_emballage_etape_check CHECK (((etape)::text = ANY ((ARRAY['AFFINAGE'::character varying, 'PREPARATION_VENTE'::character varying])::text[])))
);


--
-- Name: consommation_emballage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE consommation_emballage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME consommation_emballage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cout_production_lot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE cout_production_lot (
    id bigint NOT NULL,
    cout_amortissement numeric(19,4) NOT NULL,
    cout_emballage numeric(19,4) NOT NULL,
    cout_energie numeric(19,4) NOT NULL,
    cout_lait numeric(19,4) NOT NULL,
    cout_main_oeuvre numeric(19,4) NOT NULL,
    cout_matieres numeric(19,4) NOT NULL,
    cout_par_kg numeric(19,4) NOT NULL,
    cout_par_unite numeric(19,4) NOT NULL,
    cout_total numeric(19,4) NOT NULL,
    date_calcul timestamp(6) without time zone NOT NULL,
    nombre_unites_finales integer NOT NULL,
    fabrication_id bigint NOT NULL
);


--
-- Name: cout_production_lot_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE cout_production_lot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cout_production_lot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cout_production_manuel; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE cout_production_manuel (
    id bigint NOT NULL,
    cout_unitaire numeric(19,4) NOT NULL,
    date_mise_a_jour timestamp(6) without time zone NOT NULL,
    fromage_id bigint NOT NULL,
    utilisateur_modification_id bigint
);


--
-- Name: cout_production_manuel_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE cout_production_manuel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cout_production_manuel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emballage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE emballage (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    cout_unitaire numeric(19,4) NOT NULL,
    nom character varying(120) NOT NULL,
    unite character varying(40) NOT NULL
);


--
-- Name: emballage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE emballage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME emballage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emplacement_stock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE emplacement_stock (
    id bigint NOT NULL,
    active boolean NOT NULL,
    description character varying(500),
    nom character varying(120) NOT NULL
);


--
-- Name: emplacement_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE emplacement_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME emplacement_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE equipement (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    description character varying(500),
    nom character varying(120) NOT NULL
);


--
-- Name: equipement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE equipement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME equipement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: etagere; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE etagere (
    id bigint NOT NULL,
    numero integer NOT NULL,
    ordre integer NOT NULL,
    cave_id bigint NOT NULL
);


--
-- Name: etagere_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE etagere ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME etagere_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fabrication; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE fabrication (
    id bigint NOT NULL,
    date_fabrication date,
    recette_id bigint,
    date_heure_debut timestamp(6) without time zone NOT NULL,
    duree_chauffage_minutes integer NOT NULL,
    duree_egouttage_minutes integer NOT NULL,
    nombre_fromages integer NOT NULL,
    numero_lot character varying(255) NOT NULL,
    observations text,
    origine_lait character varying(255) NOT NULL,
    poids_total_fromages numeric(38,2) NOT NULL,
    quantite_ferments numeric(38,2) NOT NULL,
    quantite_lait numeric(19,4) NOT NULL,
    quantite_presure numeric(38,2) NOT NULL,
    temperature_chauffage numeric(38,2) NOT NULL,
    temperature_lait numeric(38,2) NOT NULL,
    temperature_mise_en_moule numeric(38,2) NOT NULL,
    type_ferments character varying(255) NOT NULL,
    type_presure character varying(255) NOT NULL,
    rendement numeric(10,2),
    operateur_id bigint,
    CONSTRAINT fabrication_origine_lait_check CHECK (((origine_lait)::text = ANY ((ARRAY['TRAITE_MATIN'::character varying, 'TRAITE_SOIR'::character varying, 'MELANGE'::character varying])::text[])))
);


--
-- Name: fabrication_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE fabrication ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME fabrication_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: facture; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE facture (
    id bigint NOT NULL,
    date_facture date NOT NULL,
    mode_paiement character varying(20) NOT NULL,
    numero_facture character varying(255) NOT NULL,
    total numeric(19,2) NOT NULL,
    commande_id bigint NOT NULL,
    CONSTRAINT facture_mode_paiement_check CHECK (((mode_paiement)::text = ANY ((ARRAY['ESPECES'::character varying, 'CARTE'::character varying, 'VIREMENT'::character varying, 'CHEQUE'::character varying, 'AUTRE'::character varying])::text[])))
);


--
-- Name: facture_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE facture ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME facture_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fromage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE fromage (
    id bigint NOT NULL,
    description character varying(255),
    nom character varying(255)
);


--
-- Name: fromage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE fromage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME fromage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ligne_commande; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE ligne_commande (
    id bigint NOT NULL,
    prix_unitaire numeric(19,2) NOT NULL,
    quantite_commandee integer NOT NULL,
    commande_id bigint NOT NULL,
    fromage_id bigint NOT NULL
);


--
-- Name: ligne_commande_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE ligne_commande ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ligne_commande_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ligne_livraison; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE ligne_livraison (
    id bigint NOT NULL,
    quantite_livree integer NOT NULL,
    quantite_prevue integer NOT NULL,
    ligne_commande_id bigint NOT NULL,
    livraison_id bigint NOT NULL,
    stock_fromage_fini_id bigint NOT NULL
);


--
-- Name: ligne_livraison_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE ligne_livraison ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ligne_livraison_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: livraison; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE livraison (
    id bigint NOT NULL,
    date_livraison date NOT NULL,
    observations character varying(255),
    commande_id bigint NOT NULL,
    utilisateur_id bigint NOT NULL,
    numero_livraison character varying(40)
);


--
-- Name: livraison_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE livraison ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME livraison_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lot_affinage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE lot_affinage (
    id bigint NOT NULL,
    date_mise_en_cave date NOT NULL,
    date_sortie_prevue date NOT NULL,
    quantite_initiale integer NOT NULL,
    statut character varying(30) NOT NULL,
    fabrication_id bigint NOT NULL,
    CONSTRAINT lot_affinage_statut_check CHECK (((statut)::text = ANY ((ARRAY['EN_ATTENTE_PLACEMENT'::character varying, 'PARTIELLEMENT_PLACE'::character varying, 'EN_AFFINAGE'::character varying, 'TERMINE'::character varying])::text[])))
);


--
-- Name: lot_affinage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE lot_affinage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lot_affinage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lot_lait; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE lot_lait (
    id bigint NOT NULL,
    date_traite timestamp(6) without time zone NOT NULL,
    numero_lot character varying(80) NOT NULL,
    observations text,
    quantite numeric(19,4) NOT NULL,
    type_traite character varying(10) NOT NULL,
    cout_unitaire numeric(19,4),
    CONSTRAINT lot_lait_type_traite_check CHECK (((type_traite)::text = ANY ((ARRAY['MATIN'::character varying, 'SOIR'::character varying])::text[])))
);


--
-- Name: lot_lait_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE lot_lait ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lot_lait_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matiere_premiere; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE matiere_premiere (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    cout_unitaire numeric(19,4) NOT NULL,
    nom character varying(120) NOT NULL,
    unite_reference character varying(20) NOT NULL,
    CONSTRAINT matiere_premiere_unite_reference_check CHECK (((unite_reference)::text = ANY ((ARRAY['L'::character varying, 'ML'::character varying, 'KG'::character varying, 'G'::character varying, 'UNITE'::character varying])::text[])))
);


--
-- Name: matiere_premiere_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE matiere_premiere ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME matiere_premiere_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mouvement_stock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE mouvement_stock (
    id bigint NOT NULL,
    commentaire character varying(500),
    date_mouvement timestamp(6) without time zone NOT NULL,
    quantite integer NOT NULL,
    type character varying(20) NOT NULL,
    stock_fromage_fini_id bigint NOT NULL,
    utilisateur_id bigint NOT NULL,
    CONSTRAINT mouvement_stock_type_check CHECK (((type)::text = ANY ((ARRAY['ENTREE'::character varying, 'SORTIE'::character varying, 'AJUSTEMENT'::character varying, 'VENTE'::character varying, 'PERTE'::character varying])::text[])))
);


--
-- Name: mouvement_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE mouvement_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mouvement_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: perte_stock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE perte_stock (
    id bigint NOT NULL,
    cout_total numeric(19,4) NOT NULL,
    cout_unitaire_reference numeric(19,4) NOT NULL,
    date_heure timestamp(6) without time zone NOT NULL,
    motif character varying(500) NOT NULL,
    quantite integer NOT NULL,
    type_perte character varying(30) NOT NULL,
    stock_fromage_fini_id bigint NOT NULL,
    utilisateur_id bigint NOT NULL,
    reservation_stock_id bigint,
    CONSTRAINT perte_stock_type_perte_check CHECK (((type_perte)::text = ANY ((ARRAY['INVENDU'::character varying, 'RETOUR_CLIENT'::character varying, 'DEFAUT_AFFINAGE'::character varying, 'DLC_DDM_DEPASSEE'::character varying, 'AUTRE'::character varying])::text[])))
);


--
-- Name: perte_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE perte_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME perte_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: placement_affinage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE placement_affinage (
    id bigint NOT NULL,
    date_debut timestamp(6) without time zone NOT NULL,
    date_fin timestamp(6) without time zone,
    position_debut integer NOT NULL,
    quantite integer NOT NULL,
    lot_affinage_id bigint NOT NULL,
    rangee_id bigint NOT NULL
);


--
-- Name: placement_affinage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE placement_affinage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME placement_affinage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rangee; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE rangee (
    id bigint NOT NULL,
    capacite integer NOT NULL,
    numero integer NOT NULL,
    ordre integer NOT NULL,
    etagere_id bigint NOT NULL
);


--
-- Name: rangee_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE rangee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME rangee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recette; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE recette (
    id bigint NOT NULL,
    nom character varying(255),
    fromage_id bigint NOT NULL,
    active boolean NOT NULL,
    cout_matiere_estime numeric(19,2) NOT NULL,
    date_creation timestamp(6) without time zone NOT NULL,
    numero_version integer NOT NULL,
    variante_key character varying(36) NOT NULL,
    frequence_retournement_jours integer,
    quantite_lait_reference numeric(19,4) NOT NULL
);


--
-- Name: recette_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE recette ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME recette_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recette_ingredient; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE recette_ingredient (
    id bigint NOT NULL,
    cout_unitaire_reference numeric(19,4) NOT NULL,
    quantite numeric(19,4) NOT NULL,
    unite character varying(20) NOT NULL,
    matiere_premiere_id bigint NOT NULL,
    recette_id bigint NOT NULL,
    CONSTRAINT recette_ingredient_unite_check CHECK (((unite)::text = ANY ((ARRAY['L'::character varying, 'ML'::character varying, 'KG'::character varying, 'G'::character varying, 'UNITE'::character varying])::text[])))
);


--
-- Name: recette_ingredient_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE recette_ingredient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME recette_ingredient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: regle_amortissement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE regle_amortissement (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    cout_par_fabrication numeric(19,4) NOT NULL,
    date_debut_validite date NOT NULL,
    date_fin_validite date,
    equipement_id bigint NOT NULL
);


--
-- Name: regle_amortissement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE regle_amortissement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME regle_amortissement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: regle_cout_energie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE regle_cout_energie (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    cout_standard numeric(19,4) NOT NULL,
    date_debut_validite date NOT NULL,
    date_fin_validite date,
    type_operation character varying(30) NOT NULL,
    unite_calcul character varying(30) NOT NULL,
    CONSTRAINT regle_cout_energie_type_operation_check CHECK (((type_operation)::text = ANY ((ARRAY['CHAUFFE'::character varying, 'AFFINAGE_CAVE'::character varying, 'CHAMBRE_FROIDE'::character varying])::text[]))),
    CONSTRAINT regle_cout_energie_unite_calcul_check CHECK (((unite_calcul)::text = ANY ((ARRAY['PAR_HEURE'::character varying, 'PAR_FROMAGE_PAR_JOUR'::character varying, 'PAR_FABRICATION'::character varying])::text[])))
);


--
-- Name: regle_cout_energie_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE regle_cout_energie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME regle_cout_energie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: regle_main_oeuvre; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE regle_main_oeuvre (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    cout_horaire numeric(19,4) NOT NULL,
    date_debut_validite date NOT NULL,
    date_fin_validite date,
    duree_standard_minutes integer NOT NULL,
    type_operation character varying(30) NOT NULL,
    CONSTRAINT regle_main_oeuvre_type_operation_check CHECK (((type_operation)::text = ANY ((ARRAY['FABRICATION'::character varying, 'RETOURNEMENT'::character varying, 'LAVAGE'::character varying, 'PREPARATION_VENTE'::character varying])::text[])))
);


--
-- Name: regle_main_oeuvre_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE regle_main_oeuvre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME regle_main_oeuvre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservation_stock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE reservation_stock (
    id bigint NOT NULL,
    quantite_reservee integer NOT NULL,
    ligne_commande_id bigint NOT NULL,
    stock_fromage_fini_id bigint NOT NULL
);


--
-- Name: reservation_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE reservation_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reservation_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: soin_affinage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE soin_affinage (
    id bigint NOT NULL,
    date_heure timestamp(6) without time zone NOT NULL,
    etat_croute character varying(255),
    observation character varying(1000),
    type character varying(20) NOT NULL,
    lot_affinage_id bigint NOT NULL,
    utilisateur_id bigint NOT NULL,
    CONSTRAINT soin_affinage_type_check CHECK (((type)::text = ANY ((ARRAY['RETOURNEMENT'::character varying, 'LAVAGE'::character varying, 'BROSSAGE'::character varying, 'OBSERVATION'::character varying, 'AUTRE'::character varying])::text[])))
);


--
-- Name: soin_affinage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE soin_affinage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME soin_affinage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_fromage_fini; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE stock_fromage_fini (
    id bigint NOT NULL,
    date_durabilite date NOT NULL,
    date_entree_stock date NOT NULL,
    quantite_initiale integer NOT NULL,
    statut character varying(20) NOT NULL,
    type_date_durabilite character varying(10) NOT NULL,
    emplacement_stock_id bigint NOT NULL,
    lot_affinage_id bigint NOT NULL,
    CONSTRAINT stock_fromage_fini_statut_check CHECK (((statut)::text = ANY ((ARRAY['DISPONIBLE'::character varying, 'EPUISE'::character varying, 'BLOQUE'::character varying])::text[]))),
    CONSTRAINT stock_fromage_fini_type_date_durabilite_check CHECK (((type_date_durabilite)::text = ANY ((ARRAY['DLC'::character varying, 'DDM'::character varying])::text[])))
);


--
-- Name: stock_fromage_fini_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE stock_fromage_fini ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME stock_fromage_fini_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: utilisateurs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE utilisateurs (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    credential_hash character varying(255) NOT NULL,
    nom character varying(150) NOT NULL,
    role character varying(20) NOT NULL,
    username character varying(100) NOT NULL,
    CONSTRAINT utilisateurs_role_check CHECK (((role)::text = ANY ((ARRAY['PROPRIETAIRE'::character varying, 'FABRICATION'::character varying, 'VENTE'::character varying])::text[])))
);


--
-- Name: utilisateurs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE utilisateurs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME utilisateurs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: utilisation_lot_lait; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE utilisation_lot_lait (
    id bigint NOT NULL,
    quantite_utilisee numeric(19,4) NOT NULL,
    fabrication_id bigint NOT NULL,
    lot_lait_id bigint NOT NULL
);


--
-- Name: utilisation_lot_lait_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE utilisation_lot_lait ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME utilisation_lot_lait_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analyse_lait analyse_lait_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY analyse_lait
    ADD CONSTRAINT analyse_lait_pkey PRIMARY KEY (id);


--
-- Name: cave cave_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY cave
    ADD CONSTRAINT cave_pkey PRIMARY KEY (id);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id);


--
-- Name: commande commande_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY commande
    ADD CONSTRAINT commande_pkey PRIMARY KEY (id);


--
-- Name: configuration_emballage configuration_emballage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY configuration_emballage
    ADD CONSTRAINT configuration_emballage_pkey PRIMARY KEY (id);


--
-- Name: consommation_emballage consommation_emballage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY consommation_emballage
    ADD CONSTRAINT consommation_emballage_pkey PRIMARY KEY (id);


--
-- Name: cout_production_lot cout_production_lot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY cout_production_lot
    ADD CONSTRAINT cout_production_lot_pkey PRIMARY KEY (id);


--
-- Name: cout_production_manuel cout_production_manuel_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY cout_production_manuel
    ADD CONSTRAINT cout_production_manuel_pkey PRIMARY KEY (id);


--
-- Name: emballage emballage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY emballage
    ADD CONSTRAINT emballage_pkey PRIMARY KEY (id);


--
-- Name: emplacement_stock emplacement_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY emplacement_stock
    ADD CONSTRAINT emplacement_stock_pkey PRIMARY KEY (id);


--
-- Name: equipement equipement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY equipement
    ADD CONSTRAINT equipement_pkey PRIMARY KEY (id);


--
-- Name: etagere etagere_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY etagere
    ADD CONSTRAINT etagere_pkey PRIMARY KEY (id);


--
-- Name: fabrication fabrication_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY fabrication
    ADD CONSTRAINT fabrication_pkey PRIMARY KEY (id);


--
-- Name: facture facture_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY facture
    ADD CONSTRAINT facture_pkey PRIMARY KEY (id);


--
-- Name: fromage fromage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY fromage
    ADD CONSTRAINT fromage_pkey PRIMARY KEY (id);


--
-- Name: lot_lait idx_lot_lait_numero; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY lot_lait
    ADD CONSTRAINT idx_lot_lait_numero UNIQUE (numero_lot);


--
-- Name: ligne_commande ligne_commande_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY ligne_commande
    ADD CONSTRAINT ligne_commande_pkey PRIMARY KEY (id);


--
-- Name: ligne_livraison ligne_livraison_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY ligne_livraison
    ADD CONSTRAINT ligne_livraison_pkey PRIMARY KEY (id);


--
-- Name: livraison livraison_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY livraison
    ADD CONSTRAINT livraison_pkey PRIMARY KEY (id);


--
-- Name: lot_affinage lot_affinage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY lot_affinage
    ADD CONSTRAINT lot_affinage_pkey PRIMARY KEY (id);


--
-- Name: lot_lait lot_lait_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY lot_lait
    ADD CONSTRAINT lot_lait_pkey PRIMARY KEY (id);


--
-- Name: matiere_premiere matiere_premiere_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY matiere_premiere
    ADD CONSTRAINT matiere_premiere_pkey PRIMARY KEY (id);


--
-- Name: mouvement_stock mouvement_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY mouvement_stock
    ADD CONSTRAINT mouvement_stock_pkey PRIMARY KEY (id);


--
-- Name: perte_stock perte_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY perte_stock
    ADD CONSTRAINT perte_stock_pkey PRIMARY KEY (id);


--
-- Name: placement_affinage placement_affinage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY placement_affinage
    ADD CONSTRAINT placement_affinage_pkey PRIMARY KEY (id);


--
-- Name: rangee rangee_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY rangee
    ADD CONSTRAINT rangee_pkey PRIMARY KEY (id);


--
-- Name: recette_ingredient recette_ingredient_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY recette_ingredient
    ADD CONSTRAINT recette_ingredient_pkey PRIMARY KEY (id);


--
-- Name: recette recette_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY recette
    ADD CONSTRAINT recette_pkey PRIMARY KEY (id);


--
-- Name: regle_amortissement regle_amortissement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY regle_amortissement
    ADD CONSTRAINT regle_amortissement_pkey PRIMARY KEY (id);


--
-- Name: regle_cout_energie regle_cout_energie_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY regle_cout_energie
    ADD CONSTRAINT regle_cout_energie_pkey PRIMARY KEY (id);


--
-- Name: regle_main_oeuvre regle_main_oeuvre_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY regle_main_oeuvre
    ADD CONSTRAINT regle_main_oeuvre_pkey PRIMARY KEY (id);


--
-- Name: reservation_stock reservation_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY reservation_stock
    ADD CONSTRAINT reservation_stock_pkey PRIMARY KEY (id);


--
-- Name: soin_affinage soin_affinage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY soin_affinage
    ADD CONSTRAINT soin_affinage_pkey PRIMARY KEY (id);


--
-- Name: stock_fromage_fini stock_fromage_fini_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY stock_fromage_fini
    ADD CONSTRAINT stock_fromage_fini_pkey PRIMARY KEY (id);


--
-- Name: livraison uk1nl3j7yj3yq91ul57uujh5lrw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY livraison
    ADD CONSTRAINT uk1nl3j7yj3yq91ul57uujh5lrw UNIQUE (commande_id);


--
-- Name: stock_fromage_fini uk4cne3qgv0jx1h5mbtx6w9skls; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY stock_fromage_fini
    ADD CONSTRAINT uk4cne3qgv0jx1h5mbtx6w9skls UNIQUE (lot_affinage_id);


--
-- Name: cout_production_lot uk64667uas3s6t1g1idh6e9u116; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY cout_production_lot
    ADD CONSTRAINT uk64667uas3s6t1g1idh6e9u116 UNIQUE (fabrication_id);


--
-- Name: emplacement_stock uk7d552qkqdd3725uqmbg55x11o; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY emplacement_stock
    ADD CONSTRAINT uk7d552qkqdd3725uqmbg55x11o UNIQUE (nom);


--
-- Name: facture uk9setotoqglu7udah6j37qc2a3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY facture
    ADD CONSTRAINT uk9setotoqglu7udah6j37qc2a3 UNIQUE (commande_id);


--
-- Name: configuration_emballage uk_configuration_emballage_fromage_emballage; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY configuration_emballage
    ADD CONSTRAINT uk_configuration_emballage_fromage_emballage UNIQUE (fromage_id, emballage_id);


--
-- Name: emballage uk_emballage_nom; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY emballage
    ADD CONSTRAINT uk_emballage_nom UNIQUE (nom);


--
-- Name: equipement uk_equipement_nom; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY equipement
    ADD CONSTRAINT uk_equipement_nom UNIQUE (nom);


--
-- Name: etagere uk_etagere_cave_numero; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY etagere
    ADD CONSTRAINT uk_etagere_cave_numero UNIQUE (cave_id, numero);


--
-- Name: lot_affinage uk_lot_affinage_fabrication; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY lot_affinage
    ADD CONSTRAINT uk_lot_affinage_fabrication UNIQUE (fabrication_id);


--
-- Name: matiere_premiere uk_matiere_premiere_nom; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY matiere_premiere
    ADD CONSTRAINT uk_matiere_premiere_nom UNIQUE (nom);


--
-- Name: rangee uk_rangee_etagere_numero; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY rangee
    ADD CONSTRAINT uk_rangee_etagere_numero UNIQUE (etagere_id, numero);


--
-- Name: recette_ingredient uk_recette_ingredient_matiere; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY recette_ingredient
    ADD CONSTRAINT uk_recette_ingredient_matiere UNIQUE (recette_id, matiere_premiere_id);


--
-- Name: recette uk_recette_variante_version; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY recette
    ADD CONSTRAINT uk_recette_variante_version UNIQUE (variante_key, numero_version);


--
-- Name: utilisation_lot_lait uk_utilisation_fabrication_lot; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY utilisation_lot_lait
    ADD CONSTRAINT uk_utilisation_fabrication_lot UNIQUE (fabrication_id, lot_lait_id);


--
-- Name: commande ukdgjirr7r8apx2ot0w75lfli84; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY commande
    ADD CONSTRAINT ukdgjirr7r8apx2ot0w75lfli84 UNIQUE (numero_commande);


--
-- Name: fabrication ukkcgtrxxlvq3s7cbe73ccth9ot; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY fabrication
    ADD CONSTRAINT ukkcgtrxxlvq3s7cbe73ccth9ot UNIQUE (numero_lot);


--
-- Name: utilisateurs ukl8ivthvih63lgxwa4uqwmbqj9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY utilisateurs
    ADD CONSTRAINT ukl8ivthvih63lgxwa4uqwmbqj9 UNIQUE (username);


--
-- Name: facture uklfqer5jriuhope9mevvxbm3sd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY facture
    ADD CONSTRAINT uklfqer5jriuhope9mevvxbm3sd UNIQUE (numero_facture);


--
-- Name: livraison ukmtenb1lfdj38cakc47fa9cb94; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY livraison
    ADD CONSTRAINT ukmtenb1lfdj38cakc47fa9cb94 UNIQUE (numero_livraison);


--
-- Name: cout_production_manuel ukn0k25amyq61t6alnkxa3nsxj4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY cout_production_manuel
    ADD CONSTRAINT ukn0k25amyq61t6alnkxa3nsxj4 UNIQUE (fromage_id);


--
-- Name: utilisateurs utilisateurs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY utilisateurs
    ADD CONSTRAINT utilisateurs_pkey PRIMARY KEY (id);


--
-- Name: utilisation_lot_lait utilisation_lot_lait_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY utilisation_lot_lait
    ADD CONSTRAINT utilisation_lot_lait_pkey PRIMARY KEY (id);


--
-- Name: idx_analyse_lot; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_analyse_lot ON analyse_lait USING btree (lot_lait_id);


--
-- Name: idx_fabrication_date_heure_debut; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fabrication_date_heure_debut ON fabrication USING btree (date_heure_debut);


--
-- Name: idx_fabrication_recette_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fabrication_recette_id ON fabrication USING btree (recette_id);


--
-- Name: idx_recette_fromage_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recette_fromage_id ON recette USING btree (fromage_id);


--
-- Name: idx_utilisation_fabrication; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_utilisation_fabrication ON utilisation_lot_lait USING btree (fabrication_id);


--
-- Name: idx_utilisation_lot; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_utilisation_lot ON utilisation_lot_lait USING btree (lot_lait_id);


--
-- Name: reservation_stock fk19ab6mwxd5d6px3u20h19bvfj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY reservation_stock
    ADD CONSTRAINT fk19ab6mwxd5d6px3u20h19bvfj FOREIGN KEY (ligne_commande_id) REFERENCES ligne_commande(id);


--
-- Name: ligne_livraison fk1aqdui2i52ra0n81yrcighjwx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY ligne_livraison
    ADD CONSTRAINT fk1aqdui2i52ra0n81yrcighjwx FOREIGN KEY (stock_fromage_fini_id) REFERENCES stock_fromage_fini(id);


--
-- Name: ligne_livraison fk1j1gxkldde0s767kip7vu8848; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY ligne_livraison
    ADD CONSTRAINT fk1j1gxkldde0s767kip7vu8848 FOREIGN KEY (livraison_id) REFERENCES livraison(id);


--
-- Name: consommation_emballage fk1mau97ygc95i2dju5s548rqgv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY consommation_emballage
    ADD CONSTRAINT fk1mau97ygc95i2dju5s548rqgv FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs(id);


--
-- Name: lot_affinage fk2gj4nfrkymb0djpf5gqu83aqf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY lot_affinage
    ADD CONSTRAINT fk2gj4nfrkymb0djpf5gqu83aqf FOREIGN KEY (fabrication_id) REFERENCES fabrication(id);


--
-- Name: consommation_emballage fk2jkepvodgol1akf78y207fit; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY consommation_emballage
    ADD CONSTRAINT fk2jkepvodgol1akf78y207fit FOREIGN KEY (emballage_id) REFERENCES emballage(id);


--
-- Name: rangee fk2yl7gvy56vbeyv99krfxirlxr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY rangee
    ADD CONSTRAINT fk2yl7gvy56vbeyv99krfxirlxr FOREIGN KEY (etagere_id) REFERENCES etagere(id);


--
-- Name: mouvement_stock fk4je2tfn4fghbkftxedaqexxdi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY mouvement_stock
    ADD CONSTRAINT fk4je2tfn4fghbkftxedaqexxdi FOREIGN KEY (stock_fromage_fini_id) REFERENCES stock_fromage_fini(id);


--
-- Name: cout_production_manuel fk4xmtq6w10iwwjgx485h4yqecb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY cout_production_manuel
    ADD CONSTRAINT fk4xmtq6w10iwwjgx485h4yqecb FOREIGN KEY (fromage_id) REFERENCES fromage(id);


--
-- Name: analyse_lait fk6dbtfywsk2obugk3buk4aqfbh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY analyse_lait
    ADD CONSTRAINT fk6dbtfywsk2obugk3buk4aqfbh FOREIGN KEY (lot_lait_id) REFERENCES lot_lait(id);


--
-- Name: recette_ingredient fk6imhy0v7m49ls08stxi7kuacw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY recette_ingredient
    ADD CONSTRAINT fk6imhy0v7m49ls08stxi7kuacw FOREIGN KEY (matiere_premiere_id) REFERENCES matiere_premiere(id);


--
-- Name: reservation_stock fk76icuqlu8s01k8236h6tugifo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY reservation_stock
    ADD CONSTRAINT fk76icuqlu8s01k8236h6tugifo FOREIGN KEY (stock_fromage_fini_id) REFERENCES stock_fromage_fini(id);


--
-- Name: commande fk79q1nginx2k3m83vi3bt3rlon; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY commande
    ADD CONSTRAINT fk79q1nginx2k3m83vi3bt3rlon FOREIGN KEY (client_id) REFERENCES client(id);


--
-- Name: fabrication fk7nk2q5c5ospjaydhxqer72w63; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY fabrication
    ADD CONSTRAINT fk7nk2q5c5ospjaydhxqer72w63 FOREIGN KEY (operateur_id) REFERENCES utilisateurs(id);


--
-- Name: placement_affinage fk7xt3il06puieu5w42onh45wio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY placement_affinage
    ADD CONSTRAINT fk7xt3il06puieu5w42onh45wio FOREIGN KEY (rangee_id) REFERENCES rangee(id);


--
-- Name: cout_production_manuel fk8uq3l4e7dcmy1udwhkbdyda88; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY cout_production_manuel
    ADD CONSTRAINT fk8uq3l4e7dcmy1udwhkbdyda88 FOREIGN KEY (utilisateur_modification_id) REFERENCES utilisateurs(id);


--
-- Name: etagere fk9j2i84dlmbx8me7gvs24l3wa0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY etagere
    ADD CONSTRAINT fk9j2i84dlmbx8me7gvs24l3wa0 FOREIGN KEY (cave_id) REFERENCES cave(id);


--
-- Name: recette_ingredient fk9nuxt33m3ltoq6xg7u1le1qr1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY recette_ingredient
    ADD CONSTRAINT fk9nuxt33m3ltoq6xg7u1le1qr1 FOREIGN KEY (recette_id) REFERENCES recette(id);


--
-- Name: cout_production_lot fk9xixhjbc67phdrw0ea8o77pkg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY cout_production_lot
    ADD CONSTRAINT fk9xixhjbc67phdrw0ea8o77pkg FOREIGN KEY (fabrication_id) REFERENCES fabrication(id);


--
-- Name: perte_stock fk_perte_reservation; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY perte_stock
    ADD CONSTRAINT fk_perte_reservation FOREIGN KEY (reservation_stock_id) REFERENCES reservation_stock(id);


--
-- Name: recette fk_recette_fromage; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY recette
    ADD CONSTRAINT fk_recette_fromage FOREIGN KEY (fromage_id) REFERENCES fromage(id);


--
-- Name: fabrication fka92cojm61hbyigl51w2407l30; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY fabrication
    ADD CONSTRAINT fka92cojm61hbyigl51w2407l30 FOREIGN KEY (recette_id) REFERENCES recette(id);


--
-- Name: ligne_commande fkaff2bjyreiuyi723relg10spm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY ligne_commande
    ADD CONSTRAINT fkaff2bjyreiuyi723relg10spm FOREIGN KEY (commande_id) REFERENCES commande(id);


--
-- Name: livraison fkbux36d9fuht90w83hta7ucdaq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY livraison
    ADD CONSTRAINT fkbux36d9fuht90w83hta7ucdaq FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs(id);


--
-- Name: stock_fromage_fini fkc6p831ih9fusowfq8skcgclq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY stock_fromage_fini
    ADD CONSTRAINT fkc6p831ih9fusowfq8skcgclq FOREIGN KEY (lot_affinage_id) REFERENCES lot_affinage(id);


--
-- Name: utilisation_lot_lait fkcvs1rolkir1l1xrl1di4ssmqx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY utilisation_lot_lait
    ADD CONSTRAINT fkcvs1rolkir1l1xrl1di4ssmqx FOREIGN KEY (lot_lait_id) REFERENCES lot_lait(id);


--
-- Name: regle_amortissement fkd20dr2re6hj2kia6mfwqm0a06; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY regle_amortissement
    ADD CONSTRAINT fkd20dr2re6hj2kia6mfwqm0a06 FOREIGN KEY (equipement_id) REFERENCES equipement(id);


--
-- Name: configuration_emballage fkdaxs6swusnyglypidd3r7of4o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY configuration_emballage
    ADD CONSTRAINT fkdaxs6swusnyglypidd3r7of4o FOREIGN KEY (emballage_id) REFERENCES emballage(id);


--
-- Name: perte_stock fke14fen1094gm9ad3puove2x75; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY perte_stock
    ADD CONSTRAINT fke14fen1094gm9ad3puove2x75 FOREIGN KEY (stock_fromage_fini_id) REFERENCES stock_fromage_fini(id);


--
-- Name: soin_affinage fke6ax2j4jxfavcjid9r7dabh1c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY soin_affinage
    ADD CONSTRAINT fke6ax2j4jxfavcjid9r7dabh1c FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs(id);


--
-- Name: facture fkf4ua12k9q2aefoa1jj5velrt5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY facture
    ADD CONSTRAINT fkf4ua12k9q2aefoa1jj5velrt5 FOREIGN KEY (commande_id) REFERENCES commande(id);


--
-- Name: soin_affinage fkfprutimgo3sn4exx04y1r32ka; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY soin_affinage
    ADD CONSTRAINT fkfprutimgo3sn4exx04y1r32ka FOREIGN KEY (lot_affinage_id) REFERENCES lot_affinage(id);


--
-- Name: ligne_livraison fkhvupske4v5kuad4kklxf81wsn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY ligne_livraison
    ADD CONSTRAINT fkhvupske4v5kuad4kklxf81wsn FOREIGN KEY (ligne_commande_id) REFERENCES ligne_commande(id);


--
-- Name: utilisation_lot_lait fkk2n0ubum2yvtluh8mg3a3t5c4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY utilisation_lot_lait
    ADD CONSTRAINT fkk2n0ubum2yvtluh8mg3a3t5c4 FOREIGN KEY (fabrication_id) REFERENCES fabrication(id);


--
-- Name: consommation_emballage fkku1uwx8jp36n13l56ea3lqn4a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY consommation_emballage
    ADD CONSTRAINT fkku1uwx8jp36n13l56ea3lqn4a FOREIGN KEY (lot_affinage_id) REFERENCES lot_affinage(id);


--
-- Name: stock_fromage_fini fklch8q29jurf8tgs6s5m4m5txk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY stock_fromage_fini
    ADD CONSTRAINT fklch8q29jurf8tgs6s5m4m5txk FOREIGN KEY (emplacement_stock_id) REFERENCES emplacement_stock(id);


--
-- Name: configuration_emballage fkn8qunbtm32flxo5dgde51pnqr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY configuration_emballage
    ADD CONSTRAINT fkn8qunbtm32flxo5dgde51pnqr FOREIGN KEY (fromage_id) REFERENCES fromage(id);


--
-- Name: perte_stock fkoc3eu50xfgcp15upnrjgtni3g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY perte_stock
    ADD CONSTRAINT fkoc3eu50xfgcp15upnrjgtni3g FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs(id);


--
-- Name: livraison fkouvi45brhke9hr6sjshfjclro; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY livraison
    ADD CONSTRAINT fkouvi45brhke9hr6sjshfjclro FOREIGN KEY (commande_id) REFERENCES commande(id);


--
-- Name: mouvement_stock fkpwx5fx3uusd56txm9bx14k709; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY mouvement_stock
    ADD CONSTRAINT fkpwx5fx3uusd56txm9bx14k709 FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs(id);


--
-- Name: ligne_commande fkql11awill8tdnbhuh8ewwe7tk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY ligne_commande
    ADD CONSTRAINT fkql11awill8tdnbhuh8ewwe7tk FOREIGN KEY (fromage_id) REFERENCES fromage(id);


--
-- Name: perte_stock fkqx9snkhj4r1e1gflvhb15sdc6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY perte_stock
    ADD CONSTRAINT fkqx9snkhj4r1e1gflvhb15sdc6 FOREIGN KEY (reservation_stock_id) REFERENCES reservation_stock(id);


--
-- Name: commande fksm9mln2t3wqac6syprg52er79; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY commande
    ADD CONSTRAINT fksm9mln2t3wqac6syprg52er79 FOREIGN KEY (utilisateur_createur_id) REFERENCES utilisateurs(id);


--
-- Name: placement_affinage fkstji9xdsm20lmddvbyfufkl01; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY placement_affinage
    ADD CONSTRAINT fkstji9xdsm20lmddvbyfufkl01 FOREIGN KEY (lot_affinage_id) REFERENCES lot_affinage(id);


--
-- PostgreSQL database dump complete
